
# This file was *autogenerated* from the file /home/abdelaziz/Documents/FirmwareScanner/RsaCtfTool/lib/../sage/binary_polinomial_factoring.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100000 = Integer(100000)#!/usr/bin/sage
# Factoring integers representing them with polynomials with order=bits
# Ex: 15 = 2^0 + 2^1 + 2^2 + 2^3 -> (2^0 + 2^1) * (2^0 + 2^2) -> 3*5
# It works well with mersenne primes but not with other composites.

import sys
sys.setrecursionlimit(_sage_const_100000 )

import math
import gmpy2
from gmpy2 import mpz

def int_to_poly(n):
  n = mpz(n)
  tmp="" 
  tmp2=[] 
  bits = n.bit_length()
  for j in range(_sage_const_0 ,bits): 
    b=int((n >> j) & _sage_const_1 ) 
    tmp = str(b) + tmp 
    if b == _sage_const_1 : 
      tmp2.append("x^%d " % (j))
  return "+".join(tmp2)

def factor_int(n,verbose=False):
  if verbose:
    print("converting to poly:")
  poly = SR(int_to_poly(n))
  if verbose:
    print(poly)
    print("finding factors:")
  factored = factor(poly)
  if verbose:
    print(factored)
    print("evaluating terms:")
  factors = []
  terms = str(factored).split(")*")
  ls = len(terms)
  if verbose:
    print(ls)
  if ls > _sage_const_0 :
    for term in terms:
      term = term.replace("(","").replace(")","")
      if verbose:
        print(term)
      factors.append(sage_eval(term,{'x':_sage_const_2 }))
  return factors
  
  if __name__ == "__main__":
    print(factor_int(Integer(sys.argv[_sage_const_1 ])))
  

